In [36]:
import collections
d = collections.OrderedDict()
d[2] = np.array([284, 284])
d[3] = np.array([183, 330])
d[4] = np.array([180, 335])


for k, v in d.items():
    print(k, v)

2 [284 284]
3 [183 330]
4 [180 335]


In [37]:
values = d.values()
values = list(values)
print(values)

[array([284, 284]), array([183, 330]), array([180, 335])]


In [38]:
from itertools import combinations
for combo in combinations(values, 2):
  print(combo)

(array([284, 284]), array([183, 330]))
(array([284, 284]), array([180, 335]))
(array([183, 330]), array([180, 335]))


In [42]:
def dist(p1, p2):
    (x1, y1), (x2, y2) = p1, p2
    return np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

for p1, p2 in combinations(values, 2):
  if  dist(p1, p2) < 10:
    print(p1,'Cerca de ', p2)

[183 330] Cerca de  [180 335]
